public enum EventType
{
    UI_CHANGED,
    LEVEL_CHANGED,

    //Game Start
    GAME_START,

    ENABLE_JOINING,

    //Player Join/Leave
    PLAYER_JOINED,
    PLAYER_LEFT,

    //Naration
    NARATION,
    N_NO_FRIENDLY_FIRE,
    N_DONT_SHOOT_FOOD,
    N_NAME_SHOT_FOOD,
    N_NAME_NEEDS_FOOD,
    N_NICE_JOB,
    N_TRY_AND_GET_OUT,
    N_NAME_LOW_HEALTH,
    N_NAME_ABOUT_TO_DIE,

    //Inventory
    WARRIOR_ADD_ITEM,
    VALKYRIE_ADD_ITEM,
    WIZZARD_ADD_ITEM,
    ELF_ADD_ITEM,

    WARRIOR_REMOVE_ITEM,
    VALKYRIE_REMOVE_ITEM,
    WIZZARD_REMOVE_ITEM,
    ELF_REMOVE_ITEM,

    //Level Start/Stop
    LEVEL_START,
    LEVEL_OVER,

    NEXT_ROUND,

    //Game Over
    GAME_OVER
}
